### ISSUE TITLE
Bulk Question Uploader

### ISSUE THREAD

**Issue by unishubh** [unishubh/starlord#24]
Write a utility to take an excel  or csv and upload questions in bulk.

**Comment by aaronleopold** [comment]
Hey there, I can try and look into this if you'd like 🙂

**Comment by unishubh** [comment]
> Hey there, I can try and look into this if you'd like 🙂

Suare, assigning this to you .

**Comment by aaronleopold** [comment]
Is there any specific structure you want the CSV to have? I'm not sure how deep you want me to go with this, since adding on validation would be a large, separate issue, but currently I created a reusable component to launch a modal and allow a user to upload a CSV. Since there's no validation, it's not being uploaded anywhere, it just provides a basic foundation for uploading files. If that's all you wanted let me know and I'll throw you a PR, otherwise let me know if I can make any changes 😄

**Comment by unishubh** [comment]
Hi, 
We need a CSV, with enough data to define the type of Question (MCQ, INT, etc) , the number of options  and correct option in case of MCQ. 
Please Note that we are not limiting the number of options.

**Comment by aaronleopold** [comment]
Currently it accepts any CSV file, as I stated there is no validation implemented on the file the user selects. If that is something you would like added I can add it, however I would need to know how you want the CSV formatted. Does this format seem appropriate?

```
type,content,numOptions,correctIndex
MCQ,"What is the best sandwich?",3,1,"None exist","Just a simple deli-meat sandwich","PBJ"
```

Note the column headers, there are 4 column headers and no header for options. It should be assumed the next X columns in a row would correlate to the numOptions field.

|  type |  content |  numOptions | correctIndex  |   |   |   |
|---|---|---|---|---|---|---|
|  MCQ |  What is the best sandwich? | 3  | 1  |  None exist | Just a simple deli-meat sandwich  | PBJ  |

**Comment by aaronleopold** [comment]
I made a PR (https://github.com/unishubh/starlord/pull/25)
